@startuml

' ========================
' ====== ENUMERADOS ======
' ========================

enum Musculo  {
CUELLO
HOMBROS
DORSALES
PECHO
BICEPS
TRICEPS
ANTEBRAZO
ZONA_LUMBAR
ESPALDA_MEDIA
TRAPECIOS
ADUCTORES
ABDUCTORES
ABDOMINALES
GLUTEOS
CUADRICEPS
ISQUIOTIBIALES
GEMELOS
}

enum DiaDeLaSemana  {
LUNES
MARTES
MIERCOLES
JUEVES
VIERNES
SABADO
DOMINGO
}

enum Genero {
HOMBRE
MUJER
OTRO
}

enum Objetivo {
    PERDER_GRASA
    GANAR_MASA_MUSCULAR
    MANTENER_PESO
}

enum NivelDeActividad {
    SEDENTARIO
    EJERCICIO_LIGERO
    EJERCICIO_MODERADO
    EJERCICIO_INTENSO 
    ATLETA
}

' ========================
' ======== CLASES ========
' ========================

class Usuario {
- idUsuario : Long
- nombre : String
- apellido1 : String
- apellido2 : String
- fechaNacimiento : LocalDate
- genero: Genero
- peso : float
- altura : int
- email : String
- telefono : String
- contrasenha : String
- nivelDeActividad : NivelDeActividad
- objetivo : Objetivo
}

class DietaCompleta {
- idDieta : Long
- nombre : String
- descripcion : String
- caloriasTotales : float
- proteinas : float
- carbohidratos : float
- grasas : float
- activa : boolean
}

class DiaEnDieta {
- idDiaEnDieta : Long
- nombre : String
- caloriasTotales : float
- proteinas : float
- carbohidratos : float
- grasas : float
- diaDeLaSemana : DiaDeLaSemana
}


class Comida {
- idComida : Long
- nombre : String
- caloriasTotales : float
- proteinas : float
- carbohidratos : float
- grasas : float
}

class Ingrediente {
- idIngrediente : Long
- nombre : String
- cantidadGramos : float
- calorias : float
- proteinas : float
- carbohidratos : float
- grasas : float
}

class Alimento {
- idAlimento : Long
- nombre : String
- caloriasPor100g : float
- proteinasPor100g : float
- carbohidratosPor100g : float
- grasasPor100g : float
}

class RutinaCompleta {
- idRutina : Long
- nombre : String
- resumen : String
}

class DiaEnRutina {
- idDiaEnDieta : Long
- nombre : String
- diaDeLaSemana : DiaDeLaSemana
}

class Ejercicio {
- idEjercicio : Long
- nombre : String
- musculoEnfocado : Musculo
}

class Serie {
- idSerie : Long
- serieAnterior : String
- repeticiones : int
- peso : int
}

' ========================
' ====== RELACIONES ======
' ========================

Usuario "1"  -- "0..*" DietaCompleta

DietaCompleta "1" -- "1..*" DiaEnDieta

Usuario "1"  -- "0..*" RutinaCompleta

DiaEnDieta "1"  -- "1..*" Comida

Comida "1"  -- "1..*" Ingrediente

Usuario "1" -- "0..*" Alimento

RutinaCompleta "1"  -- "1..*" DiaEnRutina

DiaEnRutina "1..*" -- "1..*" Ejercicio

Ejercicio "1"  -- "1..*" Serie

@enduml