spring.application.name=aplicacionSaludable

# Conexion a la BBDD

spring.datasource.url=jdbc:mysql://localhost:3306/BBDD_fitness
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Credenciales para acceder

spring.datasource.username=root
spring.datasource.password=Alexonce11_

# Uso la version 8 de mysql

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Creo las tablas de forma automatica

spring.jpa.hibernate.ddl-auto=update

# Muestro en la consola que se esta ejecutando el SQL.

spring.jpa.show-sql=true